---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serverlessops-catalog-api
  description: ServerlessOps Catalog API
  annotations:
    github.com/project-slug: ServerlessOpsIO/serverlessops-catalog-api
spec:
  type: api
  lifecycle: production
  owner: group:00gjdgxs1ur6lsu
  system: system:backstage
  providesApis:
    - resource:serverlessops-catalog-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: serverlessops-catalog-api
  description: ServerlessOps Catalog API Definition
spec:
  type: openapi
  system: system:backstage
  lifecycle: production
  owner: group:00gjdgxs1ur6lsu
  definition:
    $text: https://github.com/ServerlessOpsIO/serverlessops-catalog-api/blob/main/openapi.yaml
