---
openapi: 3.0.3
info:
  title: serverlessops-catalog-api API
  description: ServerlessOps Catalog API for Backstage
  version: 1.0.0
servers:
  - url:
      Fn::Sub: "https://${Hostname}"
    description: Production endpoint
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: "all"

paths:
  "/health":
    get:
      summary: Health check
      description: Get health of endpoint
      parameters:
        - $ref: "#/components/parameters/headerContentTypeJson"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheckResponse"
      security:
        - serverlessOpsCognitoPool:
          - Fn::Sub: https://${Hostname}/health.read
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          "application/json": |
            {
              "statusCode": 200
            }
        responses:
          "200":
            statusCode: 200
            responseTemplates:
              "application/json": |
                {
                  "healthy": true
                }

  "/catalog":
    post:
      summary: Create catalog item
      description: Create catalog item
      parameters:
        - $ref: "#/components/parameters/headerContentTypeJson"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                metadata:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                    title:
                      type: string
                    annotations:
                      type: object
                  required:
                    - name
                  additionalProperties: true
                spec:
                  type: object
                  properties:
                    owner:
                      type: string
                    type:
                      type: string
              required:
                - apiVersion
                - kind
                - metadata
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateEntityResponse"
        '400':
          description: Client failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Server failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - serverlessOpsCognitoPool:
          - Fn::Sub: https://${Hostname}/catalog.write
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateEntityFunction.Arn}/invocations"

  "/catalog/{namespace}/{kind}":
    get:
      summary: List catalog items
      description: List catalog items
      parameters:
        - $ref: "#/components/parameters/namespace"
        - $ref: "#/components/parameters/kind"
        - name: limit
          in: query
          required: false
          description: Maximum number of items to return
          schema:
            type: integer
            default: 10
        - name: offset
          in: query
          required: false
          description: Offset to start from
          schema:
            type: integer
            default: 0
        - $ref: "#/components/parameters/headerContentTypeJson"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  entities:
                    type: array
                    items:
                      type: string
        '400':
          description: Client failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Server failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '502':
          description: Unexpected upstream error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - serverlessOpsCognitoPool:
          - Fn::Sub: https://${Hostname}/catalog.read
      x-amazon-apigateway-integration:
        type: AWS
        httpMethod: POST
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:dynamodb:action/Query"
        credentials:
          Fn::Sub: ${RestApiIamRole.Arn}
        passthroughBehavior: NEVER
        requestTemplates:
          "application/json":
            Fn::Sub: |
              {
                "TableName": "${DdbTable}",
                "KeyConditionExpression": "#pk = :pk",
                "ExpressionAttributeValues": {
                  ":pk": { "S": "$input.params('namespace')/$input.params('kind')" },
                  ":itemType": { "S": "entity" }
                },
                "ExpressionAttributeNames": {
                  "#pk": "pk",
                  "#itemType": "itemType"
                },
                "FilterExpression": "#itemType = :itemType",
                "ProjectionExpression": "sk"
              }
        responses:
          "2\\d{2}":
            statusCode: 200
            responseTemplates:
              "application/json": |
                #set( $items = $input.path('$.Items') )
                {
                  "entities": [
                  #foreach($element in $items)
                    "$element.sk.S"#if($foreach.hasNext),#end

                  #end
                  ]
                }
          "4\\d{2}":
            statusCode: 400
            responseTemplates:
              "application/json": |
                {
                  "message": "$input.path('$.Message')"
                }
          "5\\d{2}":
            statusCode: 500
            responseTemplates:
              "application/json": |
                {
                  "message": "$input.path('$.Message')"
                }
          default:
            statusCode: 502
            responseTemplates:
              "application/json": |
                {
                  "message": "$input.path('$.Message')"
                }

  "/catalog/{namespace}/{kind}/{name}":
    get:
      summary: Get catalog item
      description: Get catalog item
      parameters:
        - $ref: "#/components/parameters/namespace"
        - $ref: "#/components/parameters/kind"
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/headerContentTypeJson"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Client failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Server failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - serverlessOpsCognitoPool:
          - Fn::Sub: https://${Hostname}/catalog.read
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetEntityFunction.Arn}/invocations"
    delete:
      summary: Delete catalog item
      description: Delete catalog item
      parameters:
        - $ref: "#/components/parameters/namespace"
        - $ref: "#/components/parameters/kind"
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/headerContentTypeJson"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Client failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Server failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - serverlessOpsCognitoPool:
          - Fn::Sub: https://${Hostname}/catalog.write
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteEntityFunction.Arn}/invocations"

components:
  schemas:
    CreateEntityResponse:
      type: object
      properties:
        request_id:
          type: string
      required:
        - request_id
    EmptyResponse:
      type: object
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    HealthCheckResponse:
      type: object
      properties:
        healthy:
          type: boolean
      required:
        - healthy
  parameters:
    namespace:
      name: namespace
      in: path
      required: true
      description: Requested Entity namespace
      schema:
        type: string
    kind:
      name: kind
      in: path
      required: true
      description: Requested Entity kind
      schema:
        type: string
    name:
      name: name
      in: path
      required: true
      description: Requested Entity name
      schema:
        type: string
    headerContentTypeJson:
      name: Content-Type
      in: header
      schema:
        type: string
        default: application/json; charset=utf-8
  securitySchemes:
    serverlessOpsCognitoPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        providerARNs:
          - Ref: CognitoUserPoolArn
        type: COGNITO_USER_POOLS
        identitySource: method.request.header.Authorization
        # Not sure why this breaks requests. Leaving this here as a note to not enable this
        # confoguration.
        #identityValidationExpression: "^Bearer [^\\s]+$"
